import type { ImageCategory } from "@/types";

// ── Gallery image type ────────────────────────────────────────────────────────

export interface GalleryImage {
  id: string;
  /** Public path served from /public — pass directly to next/image src. */
  url: string;
  altText: string;
  category: ImageCategory;
  sortOrder: number;
  isHero: boolean;
  /** Intrinsic width of the optimized WebP, required by next/image. */
  width: number;
  /** Intrinsic height of the optimized WebP, required by next/image. */
  height: number;
  /**
   * Tiny 10px-wide WebP encoded as base64 data URL.
   * Pass to next/image as `placeholder="blur" blurDataURL={...}`.
   * Generated by scripts/process-images.mjs.
   */
  blurDataURL: string;
}

// ── Optimized image records ───────────────────────────────────────────────────
/*
  All images are in public/assets/optimized/ as WebP files generated by
  scripts/process-images.mjs. Re-run that script after replacing any raw
  source file in public/assets/raw/.
*/

export const GALLERY_IMAGES: GalleryImage[] = [
  // ── Exterior ──────────────────────────────────────────────────────────────
  {
    id: "ext-front",
    url: "/assets/optimized/exterior-building-front.webp",
    altText: "Front elevation of SK Royal & SK Elite, Corlim, Goa",
    category: "exterior",
    sortOrder: 1,
    isHero: true,
    width: 1200,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAgCdASoKAA0ABUB8JZQCw7EfVBbRm329gAD+awt48jV2O9L8WJOV1MDoCCDoEaRfWe4Ps1IwL2EtAAA=",
  },
  {
    id: "ext-angle-1",
    url: "/assets/optimized/exterior-building-angle-1.webp",
    altText: "SK Royal & SK Elite — angled view showing full G+4 structure",
    category: "exterior",
    sortOrder: 2,
    isHero: false,
    width: 900,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoKABIAPzmGuVOvKSWisAgB4CcJZQCdACBXGGPHvBaC+MI7QAD9735+aQ5Q4C+Qg4Fyiy9u5mGCQjFdjGEGvG+p/hoMnAmqvrbniM2GS1cFf+4yAAAAAA==",
  },
  {
    id: "ext-angle-2",
    url: "/assets/optimized/exterior-building-angle-2.webp",
    altText: "SK Royal & SK Elite — second angle view with surroundings",
    category: "exterior",
    sortOrder: 3,
    isHero: false,
    width: 900,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoKABIAPzmGuVOvKSWisAgB4CcJYwCsAB8up3Y70rx1RwAA+f1V3coR66WNIuGGkVuY/NCrAE1N9T2/+L26yVWYVF7f5LABLY5qc73ggwigJAsh1JHUhfg4YQAAAA==",
  },
  {
    id: "ext-night",
    url: "/assets/optimized/exterior-building-night.webp",
    altText: "SK Royal & SK Elite illuminated at night",
    category: "exterior",
    sortOrder: 4,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAA0ABUB8JaACdACQv1EAAN2OnMma362stCewnjp4BWL2CBji3Xc5GwAPxowGKOkPO5cv5lCwgAAA",
  },

  // ── Interior ──────────────────────────────────────────────────────────────
  {
    id: "int-living",
    url: "/assets/optimized/interior-living-room.webp",
    altText: "Spacious living room in a 2 BHK unit at SK Royal & SK Elite",
    category: "interior",
    sortOrder: 5,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAA0ABUB8JZwAAlrcT8xIANZdLpoxVBmKvUgmkA9dNa7vWOzzwhIAAAA=",
  },
  {
    id: "int-entrance",
    url: "/assets/optimized/interior-entrance.webp",
    altText: "Unit entrance foyer with tiled flooring",
    category: "interior",
    sortOrder: 6,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoKAA0ABUB8JZQAAlwnknMgAPyyH8Mz70B28ZcjxXpwqENIWpXZznCRLhMh5wzo616GzEwOokAAAA==",
  },
  {
    id: "int-kitchen",
    url: "/assets/optimized/interior-kitchen.webp",
    altText: "Modular kitchen with granite counter and tiled backsplash",
    category: "interior",
    sortOrder: 7,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAA0ABUB8JZwAAxQBfPkxoAAA4nTOdDSW4GbZ6ppaSNuvdU7TvnAdC8e+d7mj03AAAA==",
  },
  {
    id: "int-balcony-1",
    url: "/assets/optimized/interior-balcony-1.webp",
    altText: "Balcony view from a 2 BHK unit — open skies over Corlim",
    category: "interior",
    sortOrder: 8,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAgCdASoKAA0ABUB8JQBOkCYjFaTTiLB/AAD31FJcOUxS2sRvjHXDRqWif1MYx1jwv6QuAAA=",
  },
  {
    id: "int-balcony-2",
    url: "/assets/optimized/interior-balcony-2.webp",
    altText: "Second balcony perspective showing neighbourhood greenery",
    category: "interior",
    sortOrder: 9,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAwAgCdASoKAA0ABUB8JZQAAsaZr0kMjKEygAD85fJ3TVynbWpf/7JXyiVwc1/Wy9muV60k5sMlpQgA",
  },
  {
    id: "int-bath-1",
    url: "/assets/optimized/interior-bathroom-1.webp",
    altText: "Attached bathroom with premium sanitary fittings",
    category: "interior",
    sortOrder: 10,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAA0ABUB8JZQAAxakM1BbGAD7Imdd78Klifobj+TI3jkw7mmJ+Mc3emJvxgSERrpmo9jgAAA=",
  },
  {
    id: "int-bath-2",
    url: "/assets/optimized/interior-bathroom-2.webp",
    altText: "Second bathroom with full-height wall tiles",
    category: "interior",
    sortOrder: 11,
    isHero: false,
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoKAA0ABUB8JYgC7ADcZ9Du7TgAAM3jih1zc9hGUodSRWRTD1Cm0hZb/NWoqrG+tonaVk4QAAA=",
  },

  // ── Floor Plan ────────────────────────────────────────────────────────────
  {
    id: "fp-typical",
    url: "/assets/optimized/floor-plan-typical.webp",
    altText: "Typical floor plan — 2 BHK layout, 102–103 sqm",
    category: "floor-plan",
    sortOrder: 12,
    isHero: false,
    width: 1422,
    height: 1008,
    blurDataURL:
      "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACQAQCdASoKAAcABUB8JQBOgCDQUIAA/esCwNNCPW9OZpInJ1Ewg+w/xHGRPObPEsX1iiAA",
  },
];

// ── Query helpers ─────────────────────────────────────────────────────────────

/** Returns images filtered by category, sorted by sortOrder. */
export function getImagesByCategory(category: ImageCategory): GalleryImage[] {
  return GALLERY_IMAGES.filter((img) => img.category === category).sort(
    (a, b) => a.sortOrder - b.sortOrder,
  );
}

/** Returns the designated hero image. */
export function getHeroImage(): GalleryImage {
  const hero = GALLERY_IMAGES.find((img) => img.isHero);
  if (!hero) throw new Error("No hero image designated in GALLERY_IMAGES");
  return hero;
}
